#!/bin/python3

import math
import os
import random
import re
import sys

#
# Complete the 'repeatedString' function below.
#
# The function is expected to return a LONG_INTEGER.
# The function accepts following parameters:
#  1. STRING s
#  2. LONG_INTEGER n
#

def repeatedString(s, n):
    # Write your code here
    cnt_a=s.count('a')
    
    len_s=len(s)
    
    cnt = cnt_a * (n//len_s)
    
    cnt_st=0
    
    if n%len_s !=0:
        st = s[0:(n%len_s)]
        cnt_st = st.count('a')
    
    return cnt+cnt_st
    

if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    s = input()

    n = int(input().strip())

    result = repeatedString(s, n)

    fptr.write(str(result) + '\n')

    fptr.close()
